[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
habits_escrow = "93KHLZAXkWKy6yAqoH8NNFDngShAr61sea3nVCnFJxCE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deploy-wallet.json"

[scripts]
test = "pnpm exec ts-node tests/habits_escrow.ts"
